export { default as Home } from './home'
export { default as Editor } from './editor'
export { default as Tester } from './tester'
export { default as About } from './about'
export { default as NotFound } from './notFound'