export { default as home } from './home/home.js'
export { default as editor } from './editor/editor.js'
export { default as tester } from './tester/tester.js'
export { default as about } from './about/about.js'
export { default as notFound } from './notFound/notFound.js'